service: arbitrage-checker
plugins:
  - serverless-offline
  - serverless-plugin-typescript
  - serverless-plugin-optimize
provider:
  name: aws
  runtime: nodejs10.x
  region: eu-central-1
  environment:
    OPPORTUNITY_TABLE: ${self:service}-opportunity-${opt:stage, self:provider.stage}

functions:
  app:
    handler: index.helloWorld
    events:
      - schedule: rate(1 minute)

package:
  individually: true
