version: '3.2'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_arbitrage
    ports:
      - '4562-4584:4562-4584'
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=sqs,dynamodb,cloudwatch
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
      - HOSTNAME_EXTERNAL=localhost
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
